jeleedev/wecode26-study

Algorithm/jieun/Searching/DFS_and_BFS_example.py

- 탐색
<br />
1. BFS / DFS 예제 추가
<br />
-

Add: DFS, BFS example

---

Algorithm/jieun/Programmers/로또의 최고순위와 최저순위.py

- 프로그래머스 Lv1. 그리디 문제 [link](https://programmers.co.kr/learn/courses/30/lessons/77484?language=python3)
<br />
1. 두개의 리스트 교집합 구하기
- set함수를 이용하여 교집합 리스트 구현 
```
list_a = [1, 2, 3]
list_b = [2, 3, 4, 5, 6]
intersection = (set(list_a) & set(list_b))
```
<br />
-

프로그래머스 Lv1.로또의 최고순위와 최저순위 풀이

---

Algorithm/jaewon/002_linked_list.py
Algorithm/jaewon/003_double_linked_list.py

- linked_list & double_linked_list
<br />
1. linked_list
- linked_list create, delete 구현
2. double_linked_list
- double_linked_list create, search, insert 구현
<br />
- 없음

Add: lined_list and double_linked_list

---

Algorithm/hwayeon/001_selection_sort.py

- 정렬 알고리즘
<br />
1. 정렬 알고리즘
- 선택정렬 알고리즘 문제 해결하기
<br />
- 없음

Add: selection_sort

---

Algorithm/jaewon/004_binary_search.py

- 이진탐색(binary_search)
<br />
1. 단순탐색보다 빠른 이진 탐색입니다.
- 이진탐색은 O(NlogN)의 시간복잡도를 가집니다.
<br />
- 없어요~~!

Add: binary_search

---

Algorithm/jieun/Programmers/신규 아이디 추천.py

- 2021 KAKAO BLIND RECRUITMENT 문제
- 유형 : 구현
<br />
1. 정규식을 사용한 문자열 컨트롤
- 
-  
2. 
- 
- 
<br />
-

Add: 프로그래머스 Lv1.신규 아이디 추천

---

Algorithm/jieun/Programmers/숫자 문자열과 영단어.py

- 2021 카카오 채용 연계형 인턴십
- 유형 : 구현
<br />
1. replace 함수를 사용하는 문제
2. Array or Dictionary 형태로 문제를 풀 수 있다.
---
**Key 추출**
1. dic.keys()
2. for k in dic.keys() == for k in dic
3. key in dic ------> key가 있는지 확인 후 Ture or False 반환
**Value 추출**
1. dic.values()
2. dic[key]
3. dic.get(key)
**Key & Value 추출**
1. dic.items()
2. for k in dic.items() --------> tuple 형태로 반환
---
<br />
-

Add: 프로그래머스 Lv1.숫자 문자열과 영단어

---

Algorithm/jaewon/005_recursive.py

- 재귀 호출
<br />
1. 재귀 호출
- 리스트합
- 팩토리얼
- 피보나치
<br />
- 없음

Add: recursive

---

DataStructure/README.md

- 스택과 큐의 차이
<br />
1. 스택은 후입선출(LIFO)의 데이터 입출력 방식의 자료구조다.
2. 큐는 선입선출(FIFO)의 데이터 입출력 방식의 자료구조다. 
3. 스택과 큐은 데이터 처리 정책이 다르고 이에 따라 데이터의 처리가 이뤄지는 장소가 다르다.
<br />
- 없음

Add: stack and queue

---

Algorithm/jieun/Programmers/없는 숫자 더하기.py
Algorithm/jieun/Programmers/키패드 누르기.py

- 시뮬레이션 문제(카카오 인턴쉽)
- 기본 계산 문제
<br />
1. 
- 
-  
2. 
- 
- 
<br />
-

Add: 프로그래머스 Lv1.없는 숫자 더하기, 키패드 누르기

---

.gitignore
Database/README.md
Python/README.md
WebBase/README.md

- database 목차 수정
- webbase 목차 수정
- python 목차 추가

Modify: 전체적인 목차 수정 및 추가

---

Python/README.md

Modify: python 목차 수정

---

Algorithm/jaewon/006_prime_number.py

- 소수구하기 3가지 방법
<br />
1. O(N) 소수 구하기
2. O(sqrt(N)) 소수 구하기
3. O(N log log N) 소수 구하기
<br />
- 없음

Add: prime number

---

Python/README.md

Modify: Reference 수정

---

Algorithm/minjeong/python 100제/question001.py

- 
<br />
python 100제 문제 1
- 리스트 요소 삭제

Add: python 100제 문제1

---

Algorithm/jaewon/007_heap.py

- heap에 node 추가하기 구현
<br />
1. heap에 node 추가
- 힙은 완전 이진 트리이므로, 첫 데이터가 삽입되면 Root Node가 됨
- 추가로 데이터가 삽입되면, 왼쪽 Node가 있는지 판단하여 없으면 왼쪽 Node에 넣고, 인쪽 Node가 이미 있다면 오른쪽 Node를 탐색하여 없으면 넣음
- 오른쪽 Node까지 있다면, 다시 왼쪽 Node의 자식들이 존재하는지를 확인하여 왼쪽부터 삽입함
- Swap의 방법은 삽입시킨 Node의 값과 부모 Node의 값을 비교하여 삽입한 Node의 값이 더 크다면 크지 않을 때 까지 계속 Swap을 진행(Max Heap의 경우)
- 즉, 완전 이진 트리의 규칙 대로 왼쪽부터 자리를 잡게한 뒤, 삽입된 위치에서 자신의 값과 부모 Node의 값을 비교해 Swap함
<br />
- 다음에는 heap에서 node를 삭제하는 방법을 올릴게요!

Add: insert node to heap

---

Algorithm/jieun/Programmers/음향더하기.py
Network/README.md

- 프로그래머스 구현문제
<br />
1. 
- 
-  
2. 
- 
- 
<br />
-

Network 수정, 프로그래머스 알고리즘 풀이

---

Python/README.md
WebBase/README.md

Modify: python, webbase 목차 수정

---

Algorithm/jaewon/007_heap.py

- heap 알고리즘
<br />
1. heap에서 node 추가
2. heap에서 node 삭제
<br />
- 없음

Modified: add node delete from heap

---

Algorithm/jaewon/007_heap.py
Algorithm/jaewon/008_stack_queue

- Heap에서 삭제 구현, Stack과 Queue
<br />
1. Stack
- FILO : First In Last Out
2. Queue
- FIFO : First In First Out
<br />
- 없음

Add: Stack and Queue, Delete in Heap

---

Algorithm/hwayeon/JS_100/question001.js
Algorithm/hwayeon/python_100/question001.py

- 리스트의 삭제
- 배열의 삭제
<br />
1. 리스트의 삭제 
2. 배열의 삭제
<br />
-

Add: Algorithm

---

Algorithm/jaewon/010_DFS.py

- DFS 구현
<br />
1. DFS 란?
- DFS(깊이 우선 탐색)는 일단 탐색할 수 있을 때까지 깊게 탐색하고, 더이상 탐색할 대상이 없으면 지나친 갈림길이 있던 노드로 되돌아가 계속 깊이를 기준으로 탐색하는 방식임
2. 시간 복잡도
- DFS에서 Node의 수를 V, 간선의 수를 E라고 할 때, 시간 복잡도는 O(V+E)
<br />
- 없음

Add: DFS in tree

---

Infrastructure/README.md

- Docker Image와 Continaer의 차이, 그리고 Docker Compose를 사용하는 이유
<br />
1. Docker Image와 Container란?
- Docker Image란 서비스 운영에 필요한 서버 프로그램, 소스코드 및 라이브러리, 컴파일된 실행 파일을 묶은 형태이다.
- Docker Image를 실행(run)한 상태로 응용프로그램 자체를 캡슐화하여 독립적인 공간에서 동작시키는 기술을 Docker Container라 한다.
2. Docker Compose를 사용하는 이유.
- Docker를 실행시키기 위한 여러 명령어를 File을 통해 명시적으로 관리한다.
- Docker Compose를 사용하면, 여러 컨테이너를 한번에 Build하고 Run시킬 수 있다.
- 뿐만아니라 컨테이너 간 가상 네트워크를 손쉽게 연결할 수 있고, 컨테이너간 의존성도 제어할 수 있다.
<br />
- 없음

Add: Docker Compose in Infrastructure

---

Algorithm/jaewon/python_100/001_010.py

- python 100제(1번~10번 문제)
<br />
- 문제1 : 리스트의 삭제
- 문제2 : 리스트의 내장함수
- 문제3 : 변수의 타입
- 문제4 : 변수의 타입2
- 문제5 : for문 계산
- 문제6 : False
- 문제7 : 변수명
- 문제8 : 딕셔너리 키 이름 중복
- 문제9 : sep과 end를활용한 출력방법
- 문제10 : 별 찍기
<br />
- 없음

Add: Python 100 start. 0-10 Done.

---

Algorithm/jaewon/python_100/011_020.py

- python 100제(10번~20번)
<br />
- 문제11 : for를 이용한 기본 활용
- 문제12 : 게임 캐릭터 클래스 만들기
- 문제13 : 몇 번째 행성인가요?
- 문제14 : 3의 배수 인가요?
- 문제15 : 자기소개
- 문제16 : 로꾸거
- 문제17 : 놀이기구 키 제한
- 문제18 : 평균 점수
- 문제19 : 제곱을 구하자
- 문제20 : 몫과 나머지
<br />
- 없음

Add: python 100, 10~20 done.

---

Django/README.md

- Offset 기반 Pagination & Cursor 기반 Pagination
<br />
1. Offset 기반 Pagination
- offset-based-pagination은 건너띌 row의 수를 offset으로한 뒤 제한할 row의 수를 limit으로 하여 데이터를 pagination하는 기법입니다.
- offset-based-pagination는 구현이 쉽고 직관적이며, 네트워크 자원을 효율적으로 사용하기 위한 방법으로 전통적으로 사용되어왔습니다.
2. Cursor 기반 Pagination
- cursor-based pagination은 cursor 개념을 사용하여 사용자에게 응답해준 마지막 데이터 기준으로 다음 n개 응답하는 방식입니다.
- 즉, n개의 row를 skip 한 다음 10개 주세요가 아니라, 이 row 다음꺼부터 10개 주세요를 요청하는 방식입니다.
- 이에 cursor-based pagination은 실무에서 주로 사용되며 데이터가 잦은 수정이 반복되더라도 누락 및 중복 이슈가 없고, 빠르다는 장점이 있습니다.
<br />
- 없음

Add: offset-based-pagination and cursor-based-pagination

---

Algorithm/jaewon/python_100/021_030.py

- python 100제 뿌수기(21번-30번)
<br />
- 문제21 : set은 어떻게 만드나요?
- 문제22 : 배수인지 확인하기
- 문제23 : OX문제
- 문제24 : 대문자로 바꿔주세요!
- 문제25 : 원의 넓이를 구하세요
- 문제26 : 행성 문제2
- 문제27 : 딕셔너리 만들기
- 문제28 : 2-gram
- 문제29 : 대문자만 지나가세요    
- 문제30 : 문자열 속 문자 찾기
<br />
- 없음

Add: python 100,, 021-030 done.

---

Algorithm/jaewon/python_100/031_040.py

- python 100제(31번~40번)
<br />
- 문제31 : 파이썬 자료형의 복잡도
- 문제32 : 문자열 만들기
- 문제33 : 거꾸로 출력하
- 문제34 : sort 구현하기
- 문제35 : Factory 함수 사용하기
- 문제36 : 구구단 출력하기
- 문제37 : count 사용하기
- 문제38 : 호준이의 아르바이트
- 문제39 : 오타 수정하기
- 문제40 : 놀이동산에 가자
<br />
- 없음

Add: python 100. 31~40 done.

---

Python/README.md

**Instance, Static, Class Method에 대해서**
<br />
- Instance Method
- Static Method
- Class Method
- Static Method와 Class Method 공통점 및 차이점 짧게

Add: python method 정리

---

Algorithm/jaewon/python_100/041_050.py

- python 100제(41번~50번)
<br />
- 문제41 : 소수판별
- 문제42 : 2020년(datetime 모듈 사용)
- 문제43 : 10진수를 2진수로
- 문제44 : 각 자리수의 합
- 문제45 : time함수 사용하기
- 문제46 : str 자료형의 응용
- 문제47 : set 자료형의 응용
- 문제48 : 대소문자 바꿔서 출력하기
- 문제49 : 최댓값 구하기
- 문제50 : 버블정렬 구현하기
<br />
- 없음

python 100. 41~50 done

---

Algorithm/jaewon/python_100/051_060.py

- python 100제(51번~60번)
<br />
- 문제51 : merge sort를 만들어보자
- 문제52 : quick sort
- 문제53 : 괄호 문자열
- 문제54 : 연속되는 수
- 문제55 : 하노이의 탑
- 문제56 : 리스트의 함수 응용
- 문제57 : 내장함수 응용하기
- 문제58 : 콤마 찍기
- 문제59 : 빈칸채우기
- 문제60 : enumerate
<br />
- 없음

Add: python 100, 51-60 done.

---

Algorithm/jaewon/python_100/061_070.py

- python 100제(61번~70번)
<br />
- 문제61 : 문자열 압축하기
- 문제62 : 20190923출력하기
- 문제63 : 친해지고 싶어
- 문제64 : 이상한 엘레베이터
- 문제65 : 변형된 리스트
- 문제66 : 블럭탑쌓기
- 문제67 : 민규의 악수
- 문제68 : 버스 시간표
- 문제69 : 골드바흐의 추측
- 문제70 : 행렬 곱하기
<br />
- 없음

Add: python 100, 61-70 done.

---

Algorithm/jaewon/python_100/071_075.py

- python 100제(71번~75번)
<br />
- 문제71 : 깊이 우선 탐색
- 문제72 : 너비 우선 탐색
- 문제73 : 최단 경로 찾기
- 문제74 : 최장 경로 찾기
- 문제75 : 이상한 369
<br />
- 없음

Add: python 100, 71-75 done.

---

Algorithm/jaewon/python_100/076-080.py

- python 100제(76~80문제)
<br />
- 문제76 : 안전한 땅
- 문제77 : 가장 긴 공통 부분 문자열
- 문제78 : 원형테이블
- 문제79 : 순회하는 리스트
- 문제80 : 순열과 조합
<br />
- 없음

Add: python 100, 76-80 done.

---

Algorithm/jaewon/python_100/081-083.py

- python 100제(81~83번 문제)
<br />
- 문제81 : 지뢰찾기
- 문제82 : 수학 괄호 파싱
- 문제83 : 수학 괄호 파싱 2
<br />
- 없음

Add: python 100, 81-83 done.

---

Algorithm/jaewon/python_100/084-087.py

- python 100제 풀이(84번~87번)
<br />
- 문제84 : 숫자뽑기
- 문제85 : 숫자 놀이
- 문제87 : 천하 제일 먹기 대회
- 문제88 : 지식이의 게임개발
<br />
- 없음

Add: python 100, 84-87 done.

---

Algorithm/jaewon/python_100/089-091.py

- python 100제 풀이(89~91번)
<br />
- 문제89 : 지식이의 게임개발2
- 문제90 : 같은 의약성분을 찾아라!
- 문제91 : 반평균 등수
<br />
- 없음

Add: python 100, 89-91 done.

---

Algorithm/jaewon/python_100/092-094.py

- python 100제 풀이(92~94번)
<br />
- 문제92 : 키보드 고장
- 문제93 : 페이지 교체 - 선입선출 알고리즘
- 문제94 : 페이지 교체 - LRU 알고리즘
<br />
- 없음

Add: python 100, 92-94 done.

---

Algorithm/minjeong/python 100제/question044.py

Add: python 100제 문제44

---

Algorithm/jaewon/python_100/095-096.py

- python 100제 풀이(95~96번)
<br />
- 문제95 : 도장찍기
- 문제96 : 넓은 data 만들기!
<br />
- 없음

Add: python 100, 95-96 done.

---

Algorithm/jaewon/python_100/097.py

- python 100제 풀이(97번)
<br />
- 문제97 : 택배배달
<br />
- 없음

python 100, 97 done.

---

Algorithm/jaewon/python_100/098.py

- python 100제 풀이(98번)
<br />
- # 문제98 : 청길이의 패션 대회
<br />
- 없음

Add: python 100, 98 done.

---

Algorithm/jaewon/python_100/099.py

- python 100제 풀이(99번)
<br />
- 문제99 : 토끼들의 행진
<br />
- 없음

Add: python 100, 99 done.

---

Algorithm/jaewon/python_100/100.py

- python 100제 풀이(100번 문제)
<br />
- 문제100 : 퍼즐게임
<br />
- 없음

python 100, 100 done.
